services:
  inframind-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: password

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_RESOURCE_ATTRIBUTES: service.name=inframind-app

    command: ["/bin/sh", "-c", "sleep 10 && java -javaagent:/app/javaagent/opentelemetry-javaagent.jar -jar /app/target/inframind-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./javaagent:/app/javaagent
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    restart: on-failure