receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'inframind-app'
          static_configs:
            - targets: ['inframind-app:8081']
          metrics_path: /actuator/prometheus

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [debug, prometheus]

    logs:
      receivers: [otlp]
      exporters: [debug]

    traces:
      receivers: [otlp]
      exporters: [debug]